[package]
name = "spawner"
version = "0.1.0"
authors = ["Casey Primozic <me@ameo.link>"]
description = "Instance spawner and management system for the Bot4 algorithmic trading platform"

[dependencies]
uuid = { version = "0.3.1", features = ["serde", "v4"] }

algobot-util = { path = "../util", version = "*" }
